name: Build

env:
  CARGO_TERM_COLOR: always

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev \
            webkit2gtk-4.0 javascriptcoregtk-4.1 libappindicator3-dev \
            librsvg2-dev patchelf libdbus-1-dev \
            pkg-config \

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: ark-gallery.AppImage
          path: ./src-tauri/target/release/bundle/appimage/ark-gallery_*_amd64.AppImage

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          choco install -y nodejs

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload App
        uses: actions/upload-artifact@v2
        with:
          name: ark-gallery-Windows.zip
          path: ./src-tauri/target/release/bundle/
