name: Build

env:
  CARGO_TERM_COLOR: always

on: [push]

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.settings.args }}

      - name: install frontend dependencies
        run: yarn install

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        if: matrix.settings.platform == 'windows-latest'
        with:
          name: ark-gallery-Windows.zip
          path: ./src-tauri/target/release/bundle/
      - name: Upload Linux AppImage
        if: matrix.settings.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: ark-gallery.AppImage
          path: ./src-tauri/target/release/bundle/appimage/ark-gallery_*_amd64.AppImage
      - name: Upload MacOS DMG
        if: matrix.settings.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ark-gallery.dmg
          path: ./src-tauri/target/release/bundle/dmg/ark-gallery.dmg
      - name: Upload MacOS App
        if: matrix.settings.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ark-gallery.app
          path: ./src-tauri/target/release/bundle/osx/ark-gallery.app
